id: I1417FAF4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-15T04:16:54+00:00'
last_modified: '2022-06-16T08:04:56.169501+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS66030
  title: བསྟན་འགྱུར ༼ཅོ་ནེ༽
  author: ''
  base:
    A816:
      image_group_id: I1GS66032
      title: ''
      total_pages: ''
      order: 1
      base_file: A816.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
